In [1]:
import numpy as np
import pandas as pd 

df = pd.read_csv('../data/insurance_claims_processed.csv')

**Converting Binary Columns**

In [2]:
binary_cols1 = ['fraud_reported']

binary_cols2 = ['property_damage', 'police_report_available']

for col in binary_cols1:
    print(col, df[col].unique())

for col in binary_cols2:
    print(col, df[col].unique())

fraud_reported ['Y' 'N']
property_damage ['YES' '?' 'NO']
police_report_available ['YES' '?' 'NO']

In [3]:
for col in binary_cols1:
    df[col] = df[col].map({'Y': 1, 'N': 0})

for col in binary_cols2:
    df[col] = df[col].map({'YES': 1, 'NO': 0})

df[binary_cols1].head()

   fraud_reported
0               1
1               1
2               0
3               1
4               0

In [4]:
df[binary_cols2].head()

   property_damage  police_report_available
0              1.0                      1.0
1              NaN                      NaN
2              0.0                      0.0
3              NaN                      0.0
4              0.0                      0.0

**Ordinal Encoding (Manual Mapping)**

In [5]:
severity_map = {
    'Trivial Damage': 0,
    'Minor Damage': 1,
    'Major Damage': 2,
    'Total Loss': 3
}

df['incident_severity'] = df['incident_severity'].map(severity_map)
df['incident_severity'].unique()

array([2, 1, 3, 0])

**One-Hot Encoding (Nominal Features)**

In [7]:
nominal_cols = [
    'insured_sex',
    'insured_education_level',
    'insured_relationship',
    'policy_state',
    'incident_state',
    'incident_city',
    'incident_type',
    'collision_type',
    'authorities_contacted',
    'auto_make',
    'auto_model'
]

df = pd.get_dummies(df, columns=nominal_cols, drop_first=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Columns: 109 entries, age to auto_model_X6
dtypes: bool(87), float64(3), int64(14), object(5)
memory usage: 257.0+ KB

In [9]:
df.select_dtypes(include='object').columns

Index(['policy_bind_date', 'policy_csl', 'insured_occupation',
       'insured_hobbies', 'incident_date'],
      dtype='object')

In [10]:
for col in df.select_dtypes(include='object').columns:
    print(col, df[col].unique())

policy_bind_date ['2014-10-17' '2006-06-27' '2000-09-06' '1990-05-25' '2014-06-06'
 '2006-10-12' '2000-06-04' '1990-02-03' '1997-02-05' '2011-07-25'
 '2002-05-26' '1999-05-29' '1997-11-20' '2012-10-26' '1998-12-28'
 '1992-10-19' '2005-06-08' '2004-11-15' '2014-12-28' '1992-08-02'
 '2002-06-25' '2005-11-27' '1994-05-27' '1991-02-08' '1996-02-02'
 '2013-12-05' '1990-09-20' '2002-07-18' '1990-02-08' '2014-03-04'
 '2000-02-18' '2008-06-19' '2003-08-01' '1992-04-04' '1991-01-13'
 '2010-08-08' '2003-03-09' '1993-02-03' '2002-11-25' '1997-07-27'
 '1995-05-08' '2012-08-30' '2006-04-30' '2003-04-13' '2007-12-05'
 '2006-08-21' '1990-01-08' '1990-03-18' '2008-01-07' '1997-03-10'
 '2004-01-10' '1994-08-20' '2002-06-02' '1994-04-28' '2014-08-17'
 '2007-08-11' '2008-11-20' '1995-10-18' '1993-05-19' '2005-02-26'
 '1990-02-14' '1993-09-30' '2014-06-10' '2008-10-28' '2007-04-24'
 '1993-12-13' '2011-08-17' '1990-08-20' '1994-02-11' '1994-02-22'
 '2011-08-15' '1998-11-11' '1995-12-04' '2002-12-28' '2004-04-15'
 '2001-02-02' '2010-01-12' '1992-04-14' '2010-05-21' '2013-10-27'
 '1994-10-12' '1997-07-04' '2011-02-15' '1994-08-21' '1997-05-15'
 '1996-10-26' '2006-03-04' '1991-01-02' '1999-08-15' '1992-01-15'
 '1999-12-07' '1993-06-06' '2000-10-03' '2010-12-29' '1990-03-17'
 '2012-03-01' '2006-02-05' '2014-11-01' '2009-06-17' '1999-09-20'
 '1990-10-19' '1996-08-05' '2001-06-06' '2007-03-25' '2013-10-31'
 '1992-06-13' '1990-10-07' '1991-12-28' '2009-06-26' '2009-01-11'
 '2003-03-18' '2012-11-02' '2000-05-04' '1999-09-29' '1999-03-09'
 '1991-02-13' '1993-08-05' '1997-10-31' '2001-04-21' '2013-01-08'
 '2009-07-23' '1998-02-20' '2008-03-13' '1996-08-20' '2014-07-27'
 '1992-11-09' '2012-06-04' '2001-05-13' '2011-09-17' '2011-07-15'
 '2005-07-27' '2005-10-18' '1996-01-19' '2005-09-29' '1997-02-18'
 '2010-05-11' '2009-02-06' '2013-07-09' '1992-06-06' '1998-03-08'
 '2004-03-29' '2006-06-01' '1994-06-08' '1998-02-12' '2000-11-16'
 '2004-10-24' '2009-11-08' '1996-09-21' '1995-07-16' '2001-06-09'
 '2002-10-06' '1997-07-14' '1994-11-11' '2012-06-23' '2007-02-18'
 '2005-06-27' '2006-05-14' '2010-04-29' '1992-11-10' '1999-07-24'
 '1992-02-22' '2002-09-13' '2003-08-09' '2007-12-04' '2002-07-22'
 '1992-07-03' '2005-03-29' '2008-03-16' '1999-05-23' '2012-11-22'
 '1993-01-29' '2003-02-11' '1990-08-15' '2010-03-06' '1990-09-27'
 '2005-06-17' '2001-09-14' '2011-01-07' '2003-09-13' '1997-10-24'
 '2009-01-04' '1998-10-12' '1993-02-23' '1996-07-07' '2013-01-23'
 '2006-12-06' '2014-02-23' '2007-11-16' '1999-04-17' '2006-02-06'
 '1993-10-20' '2006-01-01' '2003-04-04' '2014-07-05' '1996-01-16'
 '2002-04-19' '2005-12-10' '1994-11-07' '2012-06-02' '1998-04-07'
 '2007-04-25' '2000-06-30' '1996-06-04' '2009-05-09' '2001-07-08'
 '1993-09-20' '2009-11-03' '2014-12-10' '1994-01-08' '2006-08-05'
 '2007-02-07' '2001-04-09' '1995-02-17' '1995-07-25' '2006-03-24'
 '1995-03-28' '1996-06-19' '1993-06-16' '2001-07-11' '2008-11-22'
 '1990-05-19' '2013-08-26' '1997-10-12' '2002-01-21' '1996-09-02'
 '2010-01-28' '2014-10-03' '2007-05-02' '1990-09-22' '2004-09-19'
 '1995-08-28' '2004-02-04' '2014-07-23' '1997-03-21' '1991-05-06'
 '1992-08-07' '2013-09-03' '2012-01-05' '2007-01-27' '2005-10-14'
 '1990-11-03' '2005-10-15' '1999-05-22' '2002-12-21' '2007-02-10'
 '2002-03-01' '2003-04-21' '2002-09-22' '1998-02-10' '1992-09-01'
 '1999-05-01' '1997-12-19' '2000-06-18' '1995-04-24' '2006-06-16'
 '2007-09-28' '1991-11-21' '2001-05-16' '1999-08-11' '2003-06-16'
 '1999-03-30' '1999-02-03' '2011-08-25' '2010-06-28' '2001-11-06'
 '2013-04-15' '1995-12-07' '1991-11-01' '2014-05-19' '1992-03-15'
 '2006-02-03' '2003-03-16' '2002-10-16' '1990-01-27' '2010-03-11'
 '1995-09-19' '2010-02-27' '2002-04-30' '2007-04-28' '1996-07-08'
 '2002-04-01' '2006-10-29' '2007-10-25' '2001-03-28' '1995-05-04'
 '2011-09-28' '2003-01-28' '2011-02-01' '1993-02-09' '2005-08-05'
 '2006-06-17' '1993-12-07' '2012-03-14' '1997-08-05' '2009-07-05'
 '1994-11-25' '1997-02-03' '2009-10-09' '2002-11-20' '1995-05-29'
 '2011-01-22' '2012-10-18' '1991-10-13' '2010-10-01' '2013-04-10'
 '2008-06-11' '2013-12-04' '2010-08-21' '2010-06-18' '1992-04-10'
 '1991-12-06' '1993-10-29' '1991-11-03' '2002-07-09' '2005-07-01'
 '1991-11-04' '1993-04-14' '2009-08-23' '1993-06-18' '2012-07-17'
 '1999-01-25' '1990-02-23' '2000-08-30' '2008-09-03' '1991-08-02'
 '2001-09-25' '2007-03-11' '2010-11-20' '1998-08-28' '2002-07-16'
 '1990-04-29' '1998-02-01' '2008-07-20' '1998-11-13' '2001-05-24'
 '2014-06-03' '1991-08-22' '1998-12-12' '1999-02-18' '1997-10-30'
 '1999-11-29' '2013-07-07' '2003-07-05' '2005-09-21' '1995-02-18'
 '1999-04-07' '2014-12-13' '1997-06-01' '2013-07-13' '2002-12-30'
 '1997-02-28' '1998-06-18' '1996-02-08' '2004-11-17' '2012-10-25'
 '2006-04-13' '2006-02-21' '2003-12-17' '1999-07-31' '2014-08-05'
 '2011-06-05' '1992-10-11' '2010-02-17' '2007-05-06' '1997-05-01'
 '1998-01-28' '1993-05-05' '1994-08-06' '2014-11-14' '1991-12-14'
 '2009-10-21' '1997-09-29' '2003-12-31' '2008-01-01' '2004-05-31'
 '2013-12-18' '2000-08-24' '1992-10-14' '1991-11-16' '1995-10-08'
 '2007-10-28' '2008-05-16' '2009-06-22' '2012-05-10' '2003-10-02'
 '1990-08-02' '1997-09-16' '1995-07-29' '2005-09-06' '1992-08-05'
 '1993-01-22' '1995-05-20' '1992-09-24' '2007-07-20' '1992-04-28'
 '1998-01-19' '2009-09-08' '1994-12-18' '1996-08-23' '1991-11-20'
 '1998-10-28' '2003-04-09' '1992-02-04' '2006-06-29' '1997-06-21'
 '2006-09-07' '2001-10-01' '2009-02-20' '2001-06-26' '1997-01-18'
 '2014-06-24' '1992-10-02' '2012-10-09' '1993-02-10' '1994-09-28'
 '2003-05-24' '1991-12-25' '1999-09-18' '1994-02-03' '2003-01-18'
 '2005-03-07' '2003-08-23' '2002-07-11' '2014-03-19' '1993-12-06'
 '1999-08-29' '2007-03-09' '2004-01-03' '1991-04-25' '1995-03-14'
 '2005-12-09' '2001-12-25' '1999-11-14' '2001-10-27' '1993-10-31'
 '2003-02-13' '2004-03-06' '2013-07-12' '2014-08-27' '1990-06-22'
 '2008-03-07' '1991-09-03' '2011-09-02' '2012-10-06' '2014-01-18'
 '1992-03-22' '2012-12-03' '1996-10-18' '1997-10-02' '2008-03-18'
 '2010-08-29' '2005-03-31' '2013-12-25' '2014-03-11' '1997-08-04'
 '2007-11-14' '1992-07-30' '2000-12-01' '2002-09-10' '1997-11-07'
 '1993-05-18' '1996-07-11' '1995-12-17' '2013-04-12' '1995-11-13'
 '2004-11-04' '1998-03-21' '1999-07-22' '2010-02-28' '2005-01-30'
 '2001-11-29' '2012-12-24' '1997-05-11' '1994-01-26' '2010-11-04'
 '1992-06-19' '2010-06-02' '2002-10-12' '2008-02-25' '1996-09-05'
 '1998-03-16' '2010-04-22' '2008-01-25' '2000-09-10' '2008-04-23'
 '2011-02-18' '2012-04-24' '2006-05-24' '1992-01-30' '2009-01-24'
 '1995-08-29' '2011-07-31' '2013-01-05' '1994-11-18' '2014-08-30'
 '1998-09-10' '2003-01-04' '2004-05-24' '1994-09-12' '1997-07-07'
 '1991-03-01' '2001-09-29' '2012-01-10' '2001-07-05' '1991-08-07'
 '2012-07-24' '1994-08-08' '2001-12-09' '1990-03-14' '2006-03-28'
 '2013-12-23' '1991-09-30' '2001-12-27' '2005-04-07' '2003-04-08'
 '2005-11-14' '2005-01-07' '1994-02-14' '1996-01-23' '1999-12-12'
 '2004-07-15' '2012-11-07' '2009-06-29' '2000-06-26' '2002-01-09'
 '2013-11-11' '2008-01-14' '2003-03-04' '1994-06-07' '2013-07-04'
 '2002-06-30' '2004-06-30' '1998-12-19' '2014-08-31' '2005-11-10'
 '2001-11-26' '2014-05-06' '1991-01-27' '2000-03-04' '1995-10-12'
 '2014-04-25' '2011-01-26' '1996-01-26' '1991-04-08' '2002-06-29'
 '1999-04-09' '2009-04-19' '1991-11-28' '2012-04-27' '2007-03-04'
 '2012-12-31' '2013-12-21' '2005-04-28' '1994-09-17' '2003-08-16'
 '2014-09-02' '2011-12-12' '1991-08-17' '2004-02-29' '2015-02-22'
 '1990-10-13' '1991-11-25' '1990-10-02' '2009-02-17' '2005-07-17'
 '1994-03-12' '1994-08-03' '2012-08-25' '2011-12-02' '2005-02-25'
 '2004-04-20' '2009-11-17' '2009-09-19' '2001-09-12' '1992-11-27'
 '1998-12-07' '1990-08-25' '2011-10-22' '1990-02-01' '1990-11-27'
 '2004-07-16' '1993-12-10' '1995-03-08' '2009-08-03' '1996-11-03'
 '2004-08-09' '1991-07-20' '2005-01-14' '2011-12-16' '1990-10-09'
 '1994-02-27' '2014-04-21' '2010-02-11' '1991-10-05' '1992-07-23'
 '1993-10-10' '2010-11-14' '1997-03-03' '1997-03-01' '1990-08-18'
 '2014-05-28' '2004-07-22' '2009-08-02' '2007-07-05' '2010-01-24'
 '2000-05-15' '2008-03-21' '1990-05-07' '1991-02-05' '1992-03-19'
 '2013-04-24' '2009-04-10' '2008-12-01' '2000-07-05' '2014-06-11'
 '1995-04-23' '1990-09-16' '1998-12-11' '1995-10-09' '1999-12-21'
 '2002-07-28' '1993-08-03' '2007-12-16' '2008-02-10' '2006-10-01'
 '2003-05-29' '2002-05-06' '2004-02-28' '1999-01-14' '2002-01-23'
 '1992-12-09' '1998-06-24' '2011-01-06' '2012-02-24' '2011-06-25'
 '2006-11-21' '2008-06-27' '1993-08-30' '2008-04-21' '2000-06-23'
 '2010-01-11' '1990-03-28' '1998-01-29' '2014-12-05' '2002-05-27'
 '2002-08-09' '2012-12-02' '2000-03-22' '2002-04-13' '2008-06-17'
 '1994-04-07' '1992-02-29' '1996-05-11' '2013-04-03' '2009-11-12'
 '2008-11-05' '1993-02-15' '2008-07-21' '2010-09-11' '1995-12-22'
 '1991-09-26' '1990-07-15' '2009-05-10' '1999-10-28' '1995-03-30'
 '2011-01-31' '2006-04-21' '2004-03-10' '1991-01-05' '1996-10-15'
 '1994-06-21' '1994-06-13' '2003-05-27' '1996-07-06' '2005-05-08'
 '2010-11-02' '2012-07-29' '2002-06-06' '1991-09-19' '2009-06-24'
 '1992-05-29' '2004-08-12' '2006-12-24' '2007-07-24' '1994-08-17'
 '1996-04-10' '1992-12-11' '2010-08-01' '2009-03-23' '1996-07-29'
 '1994-08-23' '1992-01-05' '1997-09-11' '2002-02-10' '1993-01-28'
 '1996-10-23' '1997-04-21' '2008-11-09' '2002-06-20' '2005-10-21'
 '2005-08-28' '2013-01-16' '2005-10-10' '2009-02-08' '2005-03-06'
 '1994-05-17' '1990-07-20' '2005-04-17' '1994-02-10' '1995-03-29'
 '2007-04-30' '2001-02-15' '2001-07-09' '2008-09-06' '2004-12-19'
 '2000-11-15' '2007-03-14' '2004-12-28' '1999-07-05' '1997-11-15'
 '2010-09-27' '2007-08-18' '1993-08-09' '1991-04-02' '2007-03-15'
 '2010-05-01' '2003-06-24' '1990-07-08' '1994-09-24' '2012-06-20'
 '2006-04-19' '2001-12-07' '2006-11-25' '1996-12-06' '2012-07-10'
 '2014-04-07' '2003-10-11' '2015-01-17' '1992-12-07' '2004-11-29'
 '2004-01-02' '2006-01-25' '1993-04-18' '2006-12-09' '1997-08-30'
 '1991-06-03' '1995-09-06' '2000-02-09' '1996-07-23' '2011-12-30'
 '1996-07-21' '1996-04-08' '2001-03-04' '2001-10-19' '2006-08-18'
 '2013-04-28' '2009-11-29' '1990-02-15' '2002-04-12' '1999-02-21'
 '2011-06-18' '1995-03-26' '1991-05-03' '2001-12-19' '2012-08-05'
 '2014-01-20' '2011-12-19' '2008-07-28' '1998-05-05' '1995-04-16'
 '1992-02-14' '2007-07-11' '2010-04-07' '1991-03-10' '1996-01-20'
 '2010-03-01' '2014-06-15' '2004-11-25' '2000-08-26' '2005-08-23'
 '1990-08-09' '2003-03-28' '2007-10-23' '1996-06-27' '1994-12-11'
 '1995-12-05' '1996-12-15' '2011-06-06' '1995-12-13' '1997-10-28'
 '1996-01-04' '2008-05-09' '2009-12-05' '2012-12-22' '1992-05-19'
 '2002-05-25' '2010-04-21' '1990-03-26' '2007-05-12' '2001-01-02'
 '2006-08-10' '2014-07-28' '2011-09-27' '2013-04-20' '1991-03-20'
 '2005-12-03' '2011-05-25' '2006-10-18' '2006-07-19' '2002-06-08'
 '2009-02-12' '2001-05-14' '2001-02-16' '1993-11-18' '1990-02-18'
 '2000-05-21' '2012-08-26' '2004-11-16' '2003-01-23' '2008-11-07'
 '1999-10-19' '1990-12-20' '1996-02-14' '2001-06-10' '2010-03-17'
 '2003-07-30' '2014-09-17' '2009-06-03' '1994-10-11' '1991-07-18'
 '2001-09-24' '2012-09-19' '1991-07-11' '1991-10-29' '1999-12-28'
 '2012-10-11' '1995-08-19' '1991-02-11' '1991-07-02' '1994-04-10'
 '2005-12-04' '2014-07-16' '2003-09-17' '2000-07-15' '2009-07-29'
 '1991-04-13' '2005-11-20' '1990-05-20' '2002-11-28' '2004-06-15'
 '2010-09-26' '1990-09-15' '2009-09-16' '1999-08-12' '2009-03-08'
 '2009-04-27' '2006-08-02' '1995-12-06' '2002-11-13' '1991-11-09'
 '1998-01-14' '2002-04-25' '2004-08-13' '1990-06-24' '1991-08-21'
 '2011-02-25' '2013-02-04' '2001-02-20' '1992-03-03' '2006-12-21'
 '2000-07-14' '1991-12-12' '2013-07-01' '1998-12-16' '2015-01-03'
 '1994-04-01' '2000-08-15' '2014-11-13' '2011-02-04' '2009-01-21'
 '1992-11-07' '1992-03-20' '1995-07-17' '2000-12-27' '1999-08-06'
 '2007-03-03' '1997-12-25' '2013-11-06' '1990-09-21' '1999-10-05'
 '1992-04-07' '2009-03-05' '1997-02-10' '1992-01-28' '2013-09-16'
 '2002-01-04' '2002-04-02' '1998-07-16' '2002-08-15' '1999-09-07'
 '2012-01-12' '1996-08-18' '1996-03-11' '1997-11-23' '2013-08-08'
 '1996-11-30' '1997-06-18' '2007-04-19' '2007-09-19' '1996-12-21'
 '2008-02-03' '2003-07-16' '1991-05-05' '1991-06-16' '2001-04-03'
 '2014-03-16' '2010-08-03' '2009-11-25' '2001-05-08' '2004-06-14'
 '1994-08-07' '2004-08-26' '2000-11-05' '1994-10-03' '2005-04-11'
 '1990-05-16' '2004-09-11' '1993-11-30' '2003-03-06' '1996-12-18'
 '1995-02-21' '2009-12-11' '2000-10-18' '2007-02-09' '2006-10-28'
 '2000-01-27' '2002-04-05' '2013-04-30' '2013-05-01' '1999-01-09'
 '2007-07-04' '1994-02-05' '2006-07-12' '2007-10-24' '2001-12-08'
 '2007-03-24' '1991-07-16' '2014-01-05' '2003-02-17' '2011-11-18'
 '1996-11-11']
policy_csl ['250/500' '100/300' '500/1000']
insured_occupation ['craft-repair' 'machine-op-inspct' 'sales' 'armed-forces' 'tech-support'
 'prof-specialty' 'other-service' 'priv-house-serv' 'exec-managerial'
 'protective-serv' 'transport-moving' 'handlers-cleaners' 'adm-clerical'
 'farming-fishing']
insured_hobbies ['sleeping' 'reading' 'board-games' 'bungie-jumping' 'base-jumping' 'golf'
 'camping' 'dancing' 'skydiving' 'movies' 'hiking' 'yachting' 'paintball'
 'chess' 'kayaking' 'polo' 'basketball' 'video-games' 'cross-fit'
 'exercise']
incident_date ['2015-01-25' '2015-01-21' '2015-02-22' '2015-01-10' '2015-02-17'
 '2015-01-02' '2015-01-13' '2015-02-27' '2015-01-30' '2015-01-05'
 '2015-01-06' '2015-02-15' '2015-01-22' '2015-01-08' '2015-01-15'
 '2015-01-29' '2015-01-19' '2015-01-01' '2015-02-10' '2015-01-11'
 '2015-02-24' '2015-01-09' '2015-01-28' '2015-01-07' '2015-01-18'
 '2015-02-28' '2015-02-12' '2015-01-24' '2015-01-03' '2015-01-16'
 '2015-02-14' '2015-02-21' '2015-02-18' '2015-02-26' '2015-01-17'
 '2015-01-27' '2015-02-11' '2015-01-12' '2015-02-06' '2015-01-20'
 '2015-02-02' '2015-02-20' '2015-02-08' '2015-02-23' '2015-03-01'
 '2015-01-14' '2015-02-19' '2015-02-09' '2015-01-26' '2015-01-23'
 '2015-01-31' '2015-02-03' '2015-02-01' '2015-02-05' '2015-02-25'
 '2015-02-16' '2015-02-13' '2015-02-04' '2015-02-07' '2015-01-04']

In [11]:
df['policy_bind_date'] = pd.to_datetime(df['policy_bind_date'])
df['policy_bind_year'] = df['policy_bind_date'].dt.year
df['policy_bind_month'] = df['policy_bind_date'].dt.month
df['policy_bind_day'] = df['policy_bind_date'].dt.day
df.drop('policy_bind_date', axis=1, inplace=True)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Columns: 111 entries, age to policy_bind_day
dtypes: bool(87), float64(3), int32(3), int64(14), object(4)
memory usage: 260.9+ KB

In [13]:
for col in df.select_dtypes(include='object').columns:
    print(col, df[col].unique())

policy_csl ['250/500' '100/300' '500/1000']
insured_occupation ['craft-repair' 'machine-op-inspct' 'sales' 'armed-forces' 'tech-support'
 'prof-specialty' 'other-service' 'priv-house-serv' 'exec-managerial'
 'protective-serv' 'transport-moving' 'handlers-cleaners' 'adm-clerical'
 'farming-fishing']
insured_hobbies ['sleeping' 'reading' 'board-games' 'bungie-jumping' 'base-jumping' 'golf'
 'camping' 'dancing' 'skydiving' 'movies' 'hiking' 'yachting' 'paintball'
 'chess' 'kayaking' 'polo' 'basketball' 'video-games' 'cross-fit'
 'exercise']
incident_date ['2015-01-25' '2015-01-21' '2015-02-22' '2015-01-10' '2015-02-17'
 '2015-01-02' '2015-01-13' '2015-02-27' '2015-01-30' '2015-01-05'
 '2015-01-06' '2015-02-15' '2015-01-22' '2015-01-08' '2015-01-15'
 '2015-01-29' '2015-01-19' '2015-01-01' '2015-02-10' '2015-01-11'
 '2015-02-24' '2015-01-09' '2015-01-28' '2015-01-07' '2015-01-18'
 '2015-02-28' '2015-02-12' '2015-01-24' '2015-01-03' '2015-01-16'
 '2015-02-14' '2015-02-21' '2015-02-18' '2015-02-26' '2015-01-17'
 '2015-01-27' '2015-02-11' '2015-01-12' '2015-02-06' '2015-01-20'
 '2015-02-02' '2015-02-20' '2015-02-08' '2015-02-23' '2015-03-01'
 '2015-01-14' '2015-02-19' '2015-02-09' '2015-01-26' '2015-01-23'
 '2015-01-31' '2015-02-03' '2015-02-01' '2015-02-05' '2015-02-25'
 '2015-02-16' '2015-02-13' '2015-02-04' '2015-02-07' '2015-01-04']

In [14]:
df['incident_date'] = pd.to_datetime(df['incident_date'])

In [15]:
df['incident_year'] = df['incident_date'].dt.year
df['incident_month'] = df['incident_date'].dt.month
df['incident_day'] = df['incident_date'].dt.day

In [16]:
df.drop('incident_date', axis=1, inplace=True)

In [17]:
df = pd.get_dummies(
    df,
    columns=['policy_csl','insured_occupation','insured_hobbies'],
    drop_first=True
)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Columns: 144 entries, age to insured_hobbies_yachting
dtypes: bool(121), float64(3), int32(6), int64(14)
memory usage: 274.5 KB

In [20]:
df.to_csv("../data/final_preprocessed_insurance_data.csv", index=False)